@startuml context-map

hide empty members

title
  This diagram shows every bounded context
  and the relationships between them
end title

package "System access" as SystemAccess {}
package "Users management" as Users {}
package "Devices management" as Devices {}
Devices --> Users
package "Tasks and automations" as Tasks {}
Tasks --> Users
Tasks -d-> Permissions
Tasks --> Devices
Tasks --> Notifications
package "Permissions" {}
Permissions --> Users
Permissions -u-> Tasks
Permissions --> Devices
package "Notifications" {}
Notifications --> Users
Notifications --> Devices

@enduml
