
@startuml permissions-domain-model

hide empty members
package Repository{
    interface Repository<Id, Entity>
}

package "Users management" as UsersManagement {
    interface UsersService <<Service>>
    struct Email
}

package "Devices management" as DevicesManagement {
    interface DevicesService <<Service>>
}

package Scripts {
    interface ScriptsService <<Service>>
}

package "Permissions" {
    interface PermissionsService <<Service>> {
        addUserDevicePermission(Token, Email, DeviceId): (UserNotFoundError | DeviceNotFoundError | TokenError)?
        removeUserDevicePermission(Token, Email, DeviceId): (UserNotFoundError | DeviceNotFoundError | TokenError)?
        ..
        canExecuteActionOnDevice(Token, DeviceId): (PermissionError | InvalidTokenError)?
        canExecuteTask(Token, TaskId): (PermissionError | InvalidTokenError | ScriptNotFoundError)?
        canEdit(Token, ScriptId): (PermissionError | InvalidTokenError | ScriptNotFoundError)?
        ..
        addToEditlist(Token, Email, ScriptId): (TokenError | UserNotFoundError | ScriptNotFoundError)?
        removeFromEditlist(Token, Email, ScriptId): (TokenError | UserNotFoundError | ScriptNotFoundError)?
        ..
        addToWhitelist(Token, Email, TaskId): (TokenError | UserNotFoundError | ScriptNotFoundError)?
        removeFromWhitelist(Token, Email, TaskId): (TokenError | UserNotFoundError | ScriptNotFoundError)?
        ..
        addToBlacklist(Token, Email, TaskId): (TokenError | UserNotFoundError | ScriptNotFoundError)?
        removeFromBlacklist(Token, Email, TaskId): (TokenError | UserNotFoundError | ScriptNotFoundError)?
    }

    ~interface UserDevicePermissionRepository<(Email, DeviceId), UserDevicePermission> <<Repository>> {
    }

    interface UserDevicePermission <<Aggregate>> {
        email: Email
        deviceId: DeviceId
    }

    ~interface EditListRepository<ScriptId, EditList> <<Repository>> {
    }

    interface EditList <<Aggregate>> {
        id: ScriptId
    }

    ~interface TaskListsRepository<TaskId, TaskLists> <<Repository>> {
    }

    interface TaskLists <<Aggregate>> {
        id: TaskId
    }

    note left of TaskLists
        Users cannot be in both 
        lists at the same time
    end note


    PermissionsService -u-> DevicesManagement.DevicesService
    PermissionsService --> UsersManagement.UsersService
    PermissionsService -u-> Scripts.ScriptsService
    PermissionsService --> UserDevicePermissionRepository
    PermissionsService --> EditListRepository
    PermissionsService --> TaskListsRepository
    UserDevicePermissionRepository ----|> Repository.Repository
    UserDevicePermissionRepository o-- UserDevicePermission
    EditList "0..*" -- "0..*" UsersManagement.Email
    EditListRepository --|> Repository.Repository
    EditListRepository o-- EditList
    TaskLists "0..*" --- "0..*" UsersManagement.Email : "blacklist >"
    TaskLists "0..*" --- "0..*" UsersManagement.Email : "whitelist >"
    TaskListsRepository --|> Repository.Repository
    TaskListsRepository o-- TaskLists

}

@enduml
