@startuml repository

package Repository{
    interface Repository<Id, Entity> {
        add(Entity): DuplicateIdError?
        update(Entity): NotFoundError?
        remove(Entity): NotFoundError?
        getAll(): Iterable<Entity>
        find(Id): Entity | NotFoundError
    }
}

@enduml
