@startuml scripts-domain-model

hide empty members
package Repository{
    interface Repository<Id, Entity>
}

package "Users management" as UsersManagement {
    interface UsersService <<Service>>
}

package "Devices management" as DevicesManagement {
    interface DevicesService <<Service>>
}

package Permissions {
    interface PermissionsService <<Service>>
}

package "Scripts" {

    interface ScriptId

    interface Script<Id extends ScriptId> <<Aggregate>> {
        id: Id
        name: String
        ~execute()
    }

    interface Task
    interface Automation {
        enabled: Boolean
    }

    interface Trigger

    struct DeviceEventTrigger extends Trigger {
        deviceId: DeviceId
        eventName: String
    }

    struct PeriodTrigger extends Trigger {
        start: DateTime
        periodSeconds: Long
    }

    interface Instruction {
        execute(ExecutionEnvironment): ExecutionEnvironment
    }
    class StartTaskInstruction extends Instruction

    class DeviceActionInstruction extends Instruction {
        deviceId: DeviceId
        actionId: DeviceActionId
        input: Any
    }

    class IfInstruction

    class IfElseInstruction

    class SendNotificationInstruction extends Instruction {
        userId: UserId
        message: String
    }

    class WaitInstruction extends Instruction {
        seconds: Long
    }

    interface ConstantInstruction<T> {
        name: String
        type: Type<T>
    }

    class CreateDevicePropertyConstantInstruction<T> extends ConstantInstruction {
        deviceId: DeviceId
        propertyId: DevicePropertyId
    }
    note bottom of CreateDevicePropertyConstantInstruction
        When creating an instance of this class
        the type will be taken by following the
        DevicePropertyId and an eventual setter.
    end note

    class CreateConstantInstruction<T> extends ConstantInstruction {
        value: T
    }

    interface Condition<T> {
        leftConstant: ConstantInstruction<T>
        rightConstant: ConstantInstruction<T>
        negate: Boolean
        evaluate(ExecutionEnvironment): Boolean
    }

    interface ConditionOperator<T> {
        evaluate(ConstantInstruction<T>, ConstantInstruction<T>): Boolean
    }

    note right of ConditionOperator
        instaces of this interface will be:
        IntEOperator
        IntGEOperator
        IntLEOperator
        IntGOperator
        IntLOperator

        (And same of Int for Double)

        StringEOperator

        ColorEOperator

        BooleanEOperator
    end note

    interface ExecutionEnvironment

    struct ConstantValue<T> {
        value: T
    }

    ExecutionEnvironment "0..*" -- "0..*" ConstantInstruction
    ConstantValue .. (ExecutionEnvironment, ConstantInstruction)

    ~interface ScriptRepository<ScriptId, Script> <<Repository>> {
    }
    ScriptRepository -l-|> Repository.Repository
    ScriptRepository o-- Script

    interface ScriptsService <<Service>> {
        getAllTasks(Token): Iterable<Task> | InvalidTokenError
        executeTask(Token, TaskId): (InvalidTokenError | ScriptNotFound | PermissionError)?
        ..
        getAllAutomations(Token): Iterable<Automation> | InvalidTokenError
        setAutomationEnable(Token, AutomationId, enable: Boolean): (InvalidTokenError | ScriptNotFound)?
    }

    Script -l[hidden] ScriptId
    Script <|-- Task : "<TaskId>"
    Script <|--- Automation : "<AutomationId>"
    Automation "1" -- "1" Trigger
    Script "1" -r- "0..*" Instruction : "{ordered}"
    IfInstruction --u-|> Instruction
    IfElseInstruction -l-|> IfInstruction
    IfInstruction "0..1" o-u- "0..*" Instruction : "then >"
    IfInstruction "1" -- "1" Condition
    IfElseInstruction "0..1" o-u- "0..*" Instruction : "else >"
    StartTaskInstruction "0..*" -- "1" Task
    Condition "0..*" -- "1" ConditionOperator
    ConstantInstruction -l-|> Instruction
    ScriptsService --> ScriptRepository
    ScriptsService -u-> Permissions.PermissionsService
    ScriptsService -u-> DevicesManagement.DevicesService
    ScriptsService -u-> UsersManagement.UsersService
}

@enduml
