@startuml tasks-and-automations-domain-model

hide empty members
package Repository{
    interface Repository<Id, Entity>
}

package "Users management" as UsersManagement {
    interface UsersService <<Service>>
}

package "Devices management" as DevicesManagement {
    interface DevicesService <<Service>>
}

package Permissions {
    interface PermissionsService <<Service>>
}

package "Tasks and automations" {

    interface ScriptId

    interface Script<Id extends ScriptId> <<Aggregate>> {
        id: Id
        name: String
        ~execute()
    }

    interface Task
    interface Automation {
        enabled: Boolean
    }

    interface Trigger

    struct DeviceEventTrigger extends Trigger {
        deviceId: DeviceId
        eventName: String
    }

    struct PeriodTrigger extends Trigger {
        start: DateTime
        periodSeconds: Long
    }

    ~interface ScriptRepository<ScriptId, Script> <<Repository>> {
    }
    ScriptRepository -l-|> Repository.Repository
    ScriptRepository o-- Script

    interface ScriptsService <<Service>> {
        getAllTasks(Token): Iterable<Task> | InvalidTokenError
        executeTask(Token, TaskId): (InvalidTokenError | ScriptNotFound | PermissionError)?
        ..
        getAllAutomations(Token): Iterable<Automation> | InvalidTokenError
        setAutomationEnable(Token, AutomationId, enable: Boolean): (InvalidTokenError | ScriptNotFound)?
    }

    Script -[hidden] ScriptId
    Script <|-- Task : "<TaskId>"
    Script <|-- Automation : "<AutomationId>"
    Automation "1" -- "1" Trigger
    ScriptsService --> ScriptRepository
    ScriptsService -u-> Permissions.PermissionsService
    ScriptsService -u-> DevicesManagement.DevicesService
    ScriptsService -u-> UsersManagement.UsersService
}

@enduml
