@startuml use-case

left to right direction

actor User
actor Admin

Admin -l-|> User

rectangle "DomoticASW system" {
    Admin -- (Add/Remove smart device)
    Admin -- (Manage users device privileges)
    Admin -- (Manage tasks whitelist/blacklist)
    usecase "User registration" as (registration)
    Admin -- (registration)
    User -- (registration)
    Admin -- (Remove user)
    Admin -- (Manage device groups)
    User -- (Read smart device properties)
    User -- (Make smart device execute an action)
    User -- (Manage tasks)
    User -- (Manage automations)
    User -- (Sub/Unsubscribe for offline devices notifications)
}

@enduml