#!/bin/sh

# Redirect output to stderr.
exec 1>&2

if ! which docker &> /dev/null; then
    echo "Docker is required"
	exit 1
fi

PROJECT_ROOT="$(pwd)/$(dirname $0)/../.."

if ! git diff --quiet --cached -- "${PROJECT_ROOT}/diagrams"; then
	echo "Generating UML diagrams"

	# Removing all the diagrams so that is a src was deleted the generated diagram will be deleted as well
	rm -f "${PROJECT_ROOT}/diagrams/generated/*"

	if docker run -v /${PROJECT_ROOT}:/data plantuml/plantuml -failfast2 -o ../generated //data/diagrams/src; then
		git add ${PROJECT_ROOT}/diagrams/generated
	else
		exit 1
	fi
fi
